# Generated by Django 4.2 on 2023-11-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producao', models.CharField(max_length=1000)),
                ('economia', models.CharField(max_length=1000)),
                ('tempo', models.CharField(max_length=1000)),
            ],
        ),
    ]
