# Generated by Django 4.2 on 2023-11-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='economia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='roi',
            name='producao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='roi',
            name='tempo',
            field=models.FloatField(),
        ),
    ]
