# Generated by Django 4.2 on 2023-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0007_rename_roi_result_roi_roiresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='roiResult',
            field=models.CharField(default='', max_length=255),
        ),
    ]
