# Generated by Django 4.2 on 2023-11-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0008_alter_roi_roiresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='producao',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
