# Generated by Django 4.2 on 2023-11-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0009_alter_roi_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='tempoROI',
            field=models.FloatField(default=None),
        ),
    ]
