# Generated by Django 4.2 on 2023-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0010_alter_roi_temporoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='economia',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='producao',
            field=models.CharField(default=0.0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='roiResult',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='tempoROI',
            field=models.FloatField(default=None, null=True),
        ),
    ]
