# Generated by Django 4.2 on 2023-11-24 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0012_alter_roi_economia_alter_roi_producao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roi',
            name='economia',
        ),
        migrations.RemoveField(
            model_name='roi',
            name='producao',
        ),
        migrations.RemoveField(
            model_name='roi',
            name='tempoROI',
        ),
    ]
