# Generated by Django 4.2.6 on 2023-10-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField(max_length=500)),
            ],
        ),
    ]
