# Generated by Django 4.2.6 on 2023-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_empresas_infocreds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoCreds',
        ),
    ]
