# Generated by Django 4.2.6 on 2023-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_empresas_infocreds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoCreds',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='rua',
            field=models.CharField(max_length=300),
        ),
    ]
