# Generated by Django 4.2.6 on 2023-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0004_delete_infocreds_alter_empresas_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='rua',
            field=models.CharField(max_length=300),
        ),
    ]
