# Generated by Django 4.2 on 2023-11-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0005_alter_empresas_nome_alter_empresas_rua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producao', models.CharField(max_length=100, null=True)),
                ('economia', models.FloatField(null=True)),
                ('tempoROI', models.FloatField(null=True)),
                ('roiResult', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
