name: Build and deploy Python app to Azure Web App - econnectfds

on:
  push:
    branches:
      - producao
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'  # Updated Python version
      
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Ensure this file is in the root of your repo
          pip install selenium
          pip install webdriver_manager

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Running tests cases
        run: python manage.py test

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'econnectfds'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0905D18BFE864B8CBAE4FEE267C44A6C }}

      - name: Set webapp URL as output
        id: set-output
        run: echo "::set-output name=webapp-url::https://${{ needs.deploy.outputs.webapp-url }}"

  output:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the webapp URL
        run: echo "The webapp URL is ${{ needs.deploy.outputs.webapp-url }}"
